import { axiosInstance } from "@/lib/axios";
import { Container, Heading, Spinner, Table, TableColumnHeader, TableHeader, TableRow } from "@chakra-ui/react"
import Head from "next/head"
import { useEffect, useState } from "react";

export default function Home() {
  const [posts, setPosts] = useState([]); // menyimpan data response GET /posts
  const [isLoading, setIsLoading] = useState(false)

  const fetchPosts = async () => {
    setIsLoading(true);
    try {
      // setTimeout(async () => {
        const postsResponse = await axiosInstance.get("/posts");

        setPosts(postsResponse.data.data);
        setIsLoading(false);
      // }, 1000)
    } catch (error) {
      console.log(error);
    }
  };

  const renderPosts = () => {
    return posts.map((product) => {
      return (
        <Table.Row key={product.id}>
          <Table.Cell>{product.id}</Table.Cell>
          <Table.Cell>{product.title}</Table.Cell>
          <Table.Cell>{product.content}</Table.Cell>
          <Table.Cell>{product.image}</Table.Cell>
        </Table.Row>
      )
    })
  }

  useEffect(() => {
    fetchPosts()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading as={"h1"}>Helo World!</Heading>
          <Table.Root size={"sm"}>
            <Table.Header>
              <Table.Row>
                <Table.ColumnHeader>ID</Table.ColumnHeader>
                <Table.ColumnHeader>TITLE</Table.ColumnHeader>
                <Table.ColumnHeader>CONTENT</Table.ColumnHeader>
                <Table.ColumnHeader>IMAGE</Table.ColumnHeader>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {renderPosts()}
              {isLoading && <Spinner />}
            </Table.Body>
          </Table.Root>
        </Container>
      </main>
    </>
  )
}
