import { usePosts } from "@/features/useFetchPosts";
import { axiosInstance } from "@/lib/axios";
import { Container, Heading, Spinner, Table, TableColumnHeader, TableHeader, TableRow } from "@chakra-ui/react"
import { useQuery } from "@tanstack/react-query";
import Head from "next/head"
import { useEffect, useState } from "react";

export default function Home() {
  const {data, isLoading} = useQuery({
    queryFn: async () => {
      const  postResponse = await axiosInstance.get("/posts");

      return postResponse;
    }
  })

  const renderPosts = () => {
    return posts.map((product) => {
      return (
        <Table.Row key={product.id}>
          <Table.Cell>{product.id}</Table.Cell>
          <Table.Cell>{product.title}</Table.Cell>
          <Table.Cell>{product.content}</Table.Cell>
          <Table.Cell>{product.image}</Table.Cell>
        </Table.Row>
      )
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading as={"h1"}>Helo World!</Heading>
          <Table.Root size={"sm"}>
            <Table.Header>
              <Table.Row>
                <Table.ColumnHeader>ID</Table.ColumnHeader>
                <Table.ColumnHeader>TITLE</Table.ColumnHeader>
                <Table.ColumnHeader>CONTENT</Table.ColumnHeader>
                <Table.ColumnHeader>IMAGE</Table.ColumnHeader>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {renderPosts()}
              {isLoading && <Spinner />}
            </Table.Body>
          </Table.Root>
        </Container>
      </main>
    </>
  )
}
